#!/bin/bash
BOLD_GREEN="\e[1;92m"
NO_FORMAT="\e[0m"
PROGRAM="./avaliaSucessor"

INPUT_FILE="./tests/assignmentExample"
POSITIONX="5"
POSITIONY="1"
echo -e "$BOLD_GREEN$PROGRAM $INPUT_FILE $POSITIONX $POSITIONY$NO_FORMAT"
$PROGRAM $INPUT_FILE $POSITIONX $POSITIONY

INPUT_FILE="./tests/mySimpleExample"
POSITIONX="1"
POSITIONY="2"
echo -e "$BOLD_GREEN$PROGRAM $INPUT_FILE $POSITIONX $POSITIONY$NO_FORMAT"
$PROGRAM $INPUT_FILE $POSITIONX $POSITIONY