#!/bin/bash
#BOLD_GREEN="\e[1;92m"
#NO_FORMAT="\e[0m"
PROGRAM="./avaliaSucessor"
INPUT_FILE=$1
ROW=$2
COLUMN=$3
$PROGRAM $INPUT_FILE $ROW $COLUMN

# test 1
#INPUT_FILE="./tests/assignmentExample"
#POSITIONX="5"
#POSITIONY="1"
#echo -e "$BOLD_GREEN$PROGRAM $INPUT_FILE $POSITIONX $POSITIONY$NO_FORMAT"
#$PROGRAM $INPUT_FILE $POSITIONX $POSITIONY

# test 2
#INPUT_FILE="./tests/mySimpleExample"
#POSITIONX="1"
#POSITIONY="2"
#echo -e "$BOLD_GREEN$PROGRAM $INPUT_FILE $POSITIONX $POSITIONY$NO_FORMAT"
#$PROGRAM $INPUT_FILE $POSITIONX $POSITIONY

